---
- hosts: all
  gather_facts: no
  become: yes
  vars:

  tasks:
  - name: get hostname
    command: /bin/hostname
    changed_when: false
    register: hostname
  
  # - name: ensure the file exist
  #   file:
  #     path: $HOME/uptime.txt
  #     state: touch

  - name: get uptime
    shell: uptime | tail > time.txt
    changed_when: false
    register: uptime

  - debug: var={{ item }}
    with_items:
      - hostname.stdout
      - uptime.stdout


  # - command: cat /tmp/result.txt
  #   register: store
  # - local_action: "copy content='{{ store.stdout }}' dest=/etc/ansible/data.txt"
  
  # - name: shell command
  #   shell: my_shell_command
  #   register: myshell_output
  # - name: copy the output to a local file
  #   copy:
  #     content: "stdout_lines"
  #     dest: "$HOME/uptime.txt"
  #   delegate_to: localhost
  #     #No worries you will do it insallah O cok Buyuktur hic korkma korkularindan Ona sigin.

  # awk '{ print $2" "$3 }'