---
- hosts: all
  gather_facts: no
  become: yes
  vars:

  tasks:
  - name: get hostname
    command: /bin/hostname
    changed_when: false
    register: hostname

  - name: get uptime
    shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
    changed_when: false
    register: uptime

  - debug: var={{ item }}
    with_items:
      - hostname.stdout
      - uptime.stdout

      #No worries you will do it insallah O cok Buyuktur hic korkma korkularindan Ona sigin.